backend:
    name: git-gateway
    branch: main
media_folder: 'public'
public_folder: 'public'
collections:
    - name: 'seminarietti'
      label: 'Seminarietti'
      folder: 'src/seminarietto'
      create: true
      slug: "{{slug}}"
      fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: '../../layouts/Seminarietto.astro'
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
